aarch64: allow disabling and enabling FIQs distinctively
theseus-os/irq_safety pull request #10
Opened 2023-09-12 15:13 UTC by NathanRoyer

Previously, FIQs and IRQs were both disabled/enabled by `enable/disable_interrupts`.
With this merged, only IRQs are affected. There are two new functions for FIQs:
`enable_fast_interrupts` & `disable_fast_interrupts`.

2023-09-12 19:18 UTC, kevinaboos requested changes
Now that we have another dimension of functionality, we need to add documentation to:
* both the regular `enable_interrupts` and `disable_interrupts` function that specifies those functions are only concerned with regular interrupts and have no impact on FIQs (on aarch64) / NMIs (on x86_64).
* both the new `enable_fast_interrupts` and `disable_fast_interrupts` function that specifies those functions are only concerned with fast interrupts (FIQs) and have no impact on regular IRQs.
* The `interrupts_enabled()` function that specifies it only considers regular IRQs when determining if interrupts are enabled.

2023-09-12 19:20 UTC, kevinaboos commented on src/held_interrupts.rs
> +        (daif & (2 << 6)) == 0
if we're only checking one bit, it's clearer to just do `1 << 7` instead of `2 << 6`, since `2 << 6` is not a common and easily-readable code pattern

2023-09-13 20:56 UTC, kevinaboos commented on src/held_interrupts.rs
> +        (daif & (2 << 6)) == 0
yes, at least in CS speak, we typically use zero-indexed terminology. So a 32-bit integer would go from bit 0 (the zeroeth/0th bit) to bit 31 (the 31st bit)

2023-09-13 21:03 UTC, NathanRoyer commented on src/held_interrupts.rs
> +        (daif & (2 << 6)) == 0
Ok, I'll change that too.

2023-09-13 21:35 UTC, kevinaboos approved these changes

2023-09-13 21:36 UTC, merged