Disable the interrupt before trying to lock.
theseus-os/irq_safety pull request #2
Opened 2021-06-29 14:05 UTC by Acciente717

Disable the interrupt before trying to lock.

If the interrupt is not disabled, it might happen that the mutex is successfully locked, but right before the interrupt is disabled, an interrupt fires and the current thread is preempted. If this happens, other threads waiting for the lock will be starved.

2021-06-29 18:50 UTC, kevinaboos requested changes
Hey Zhiyao, thanks and very interesting find here. I think an old version of this crate used to do that; not sure why it was changed. I can't remember, do you recall if we discussed this before, such as a couple of years ago? 

In any case, I think this change is mostly fine (see my one minor fix), although it may cause significant performance degradation (especially in a spin-lock case) due to constantly disabling interrupts in order to even _test_ the status of the lock. Of course it's most important to avoid deadlock, and one could argue that performance issues here are irrelevant because we shouldn't be using IRQ-safe locks very often.... but still.  Eventually we'll transition things to a preemption-safe lock instead of interrupt-safe, so that'll help performance issues. 

Perhaps we could address some of that performance degradation by doing something like this:
1. test the lock 
2. if not available, return to step 1 (without modifying the interrupt enable bit at all)
3. if available, hold interrupts and then attempt to acquire the lock again
4. if not available, drop the held interrupts and return to step 1
5. if available, interrupts are already held and we proceed as normal

I realize the test-then-acquire sequence isn't atomic, but that's okay. It avoids disabling interrupts, which is fairly costly and can kill I/O-heavy workloads.  

We can discuss this on Slack too before settling on a final re-design.

2021-06-29 18:50 UTC, kevinaboos commented on src/mutex_irqsafe.rs
> +        let held_irq = ManuallyDrop::new(hold_interrupts());
if we place the `HeldInterrupts` object inside of a `ManuallyDrop` wrapper, then won't it not get dropped if something were to fail later on? I don't think any failures are possible here, but I think it's still much safer (and clearer) to simply hold the interrupts up top, and then place them inside of `ManuallyDrop` when we create the `MutexIrqSafeGuard`. 

So, something like this:
```rust
let held_irq = hold_interrupts();
...
    MutexIrqSafeGuard {
        held_irq: ManuallyDrop::new(held_irq),
        guard: ...
    }
...
```

Also, I think I read about some kind of new method in the `Option` type that allows us to avoid that `success.unwrap()` call (since we know it's `Some` here), but I can't remember what it is. We can save that for another PR.

2021-06-30 06:06 UTC, kevinaboos requested changes
looks good, i like the `map` combinator used in `try_lock`. 

I left one small comment.

2021-06-30 06:06 UTC, kevinaboos commented on src/mutex_irqsafe.rs
> +            }
is there any difference in the generated code of this `match` statement compared to an `if let` statement? 

e.g., 
```rust
loop {
    if let Some(guard) = self.try_lock() {
        return guard;
    }
}
```

2021-06-30 06:10 UTC, Acciente717 commented on src/mutex_irqsafe.rs
> +            }
No. The generated code of the two version is exactly same.

2021-06-30 06:18 UTC, kevinaboos commented on src/mutex_irqsafe.rs
> +            }
Great, thanks. Will merge

2021-06-30 06:18 UTC, kevinaboos approved these changes

2021-06-30 06:20 UTC, merged